# Generated by Django 3.1.7 on 2021-04-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortening', '0003_auto_20210401_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='count',
        ),
        migrations.AddField(
            model_name='link',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='abbreviated_link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
