# Generated by Django 3.1.7 on 2021-04-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortening', '0004_auto_20210402_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='abbreviated_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(),
        ),
    ]
