# Generated by Django 3.1.7 on 2021-04-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortening', '0005_auto_20210403_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='abbreviated_link',
            new_name='abbreviated_url',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='url',
        ),
    ]
